development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  database: rendezvous_test
  username: travis
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: rendezvous.production
  database: rendezvous
  username: xxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxx
